apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    role: jenkins-slave
  name: ose-jenkins-agent-nodejs
  namespace: website
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.redhat.io/openshift4/ose-jenkins-agent-nodejs
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-server
    app.kubernetes.io/component: api-server
    app.kubernetes.io/instance: api-server
  name: api-server
  namespace: website
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deployment: api-server
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: api-server
    app.kubernetes.io/component: api-server
    app.kubernetes.io/instance: api-server
  name: api-server
  namespace: website
spec:
  host: api-server-website.apps.cluster-27b6.27b6.sandbox629.opentlc.com
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: api-server
    weight: 100
  wildcardPolicy: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-server
    app.kubernetes.io/component: api-server
    app.kubernetes.io/instance: api-server
  name: api-server
  namespace: website
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: api-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: api-server
    spec:
      containers:
        - image: docker.io/cmwylie19/api-server
          imagePullPolicy: IfNotPresent
          name: api-server
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    application: origin-jenkins-agent-rust
  name: origin-jenkins-agent-rust
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "origin-jenkins-agent-rust:latest"
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: >-
      FROM
      registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7:latest

      USER root

      RUN yum repolist > /dev/null && yum-config-manager --enable
      rhel-7-server-extras-rpms &&  yum clean all &&  INSTALL_PKGS="skopeo" &&
      yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS && rpm -V
      $INSTALL_PKGS && yum clean all

      RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -y

      USER 1001
    type: Dockerfile
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers: []
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: api-server-docker
    app.kubernetes.io/instance: development-buildconfigs
  name: api-server-docker
  namespace: website
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: member:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers: []
---  
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: api-server-pipeline
  namespace: website
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/devsuperstar/cache-service.git
    # sourceSecret:
    #   name: bitbucket
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: AGENT_NAME
        value: ose-jenkins-agent-nodejs
      - name: BUILD_CONFIG_NAME
        value: member-build
      - name: ENV_TAG
        value: dev
      - name: TARGET_PROJECT
        value: api-server-dev
      - name: TARGET_PROJECT_IS
        value: api-server
      - name: TARGET_PROJECT_IS_TAG
        value: latest
      - name: QUAY_URL
        value: quay.apps.ent-ocp4-np2-har.antmdc.internal.das
      - name: QUAY_ORG
        value: api-server
      - name: QUAY_IMAGE_REPO
        value: api-server
      - name: CURRENT_IS
        value: api-server
      - name: CURRENT_IS_TAG
        value: latest
      - name: GIT_REPOSITORY_URL
        value: https://github.com/devsuperstar/cache-service.git
      - name: GIT_REPOSITORY_BRANCH
        value: master
      jenkinsfilePath: manifests/Jenkinsfile
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: QdBuCPedHi-u2kD4WLRR
      type: GitHub
