library identifier: "pipeline-library@master",
retriever: modernSCM(
    [
        $class: "GitSCMSource",
        remote: "https://github.com/redhat-cop/pipeline-library.git"
    ]   
)
pipeline{
  agent {
    label "ose-jenkins-agent-nodejs" #Same as the name of the skopeo agent imagestream
  }
  stages {
    //Note this stage is not necessary if the Jenkinsfile and the source code lives in the same branch of the same repository
    stage('Checkout Source Code') {
      steps {
        echo "Checking out source code"
            git (
                branch: "master",
               // credentialsId: "<NAMESPACE NAME>-<SECRET FOR BITBUCKET CREATED EARLIER>",
                url: "https://github.com/cmwylie19/webserver-2"
            )
        echo "Checking out code completed"
      }
    }
    /*This stage compiles the application. If the application has multiple services that reside in
      different directories then this step needs to be repeated for those services*/
    stage('Compile Common Module') {
      steps {
      //  sh 'cd <directory where the code resides> && mvn -U clean install -Dmaven.test.skip=true'
        echo 'Common module build completed'
      }
    }
    //Insert other stages here to build rest of the services
    // stage('Trigger Dockertype build in Openshift'){
    //   steps {
    //     sh '''
    //   rm -rf artifacts && mkdir -p artifacts/deployments
    //   cp -rfv <DIRECTORY_TO_DESIRED_TARGET_FOLDER>/target/*.jar artifacts
    //   cp Dockerfile artifacts
    //   '''     
    // binaryBuild(projectName: "<NAMESPACE>", buildConfigName: "<NAME OF BUILDCONFIG IN STEP 2>", buildFromPath: "artifacts")
    //   }
    // }
  }
}



